#!/usr/bin/env perl
use strict;
use warnings;

use FindBin qw($Bin);
use JSON qw();
use Path::Tiny qw(path tempfile);

my $tmpl = path("$Bin/auto_pagerize.user.js.tmpl");
my $target = path("$Bin/auto_pagerize.user.js");
my $url = 'http://wedata.net/databases/AutoPagerize/items_all.json';

die "tmpl not found: $tmpl" unless -f $tmpl;

my $tmp = tempfile;
0 == system 'sh', '-c', "curl -sL $url > $tmp" or die "curl failed: $!";
my $json = JSON->new->canonical(1)->pretty(1)->utf8(1);
my $decoded = $json->decode($tmp->slurp);
my @site_info = map { $_->{data} } @$decoded;
(my $output = $tmpl->slurp) =~ s/"%__SITEINFO__%"/$json->encode(\@site_info)/e;
$target->spew($output);
