#!/bin/bash
if git status -sb; then
  git config user.name "github-actions[bot]"
  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  git add .
  version=$(grep @version auto_pagerize.user.js | cut -wf3)
  git commit -m "[ci skip] feat: update $version"
  git remote set-url origin git@github.com:"$GITHUB_REPOSITORY"
  git push origin main
fi
