name: Update check
on:
  push:
  schedule:
    - cron: '5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: webfactory/ssh-agent@0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ./generate
      - run: ./update
