name: Update check
on:
  push:
  schedule:
    - cron: '20 * * * *'
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - run: ./generate
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ./update
